import './globals.css'
import Footer from './componentes/Footer';
import Header from './componentes/Header';




export const metadata = {
  title: 'Garcia & Caceres Gonzales',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <Header/>
{children}
      <Footer/>
      </body>
    </html>
  )
}
